home:
  local:"../sites/phest_document/output/local"
  production: "http://localhost/phest/sites/phest_document"
basetpl: "_base.tpl"
buildclear: 1
sitemap: 1
robotstxt: 1
compilejs: 1
compilecss: 1
plugins:
  -
    publish:　#README.md をコピーし、 docs/ フォルダを更新
      _button:
        label: 公開用にコピー
        type: primary
        icon: ok-circle
