# デフォルト設定
home:
  local:
  production: http://www.example.com
#起点となるテンプレート
basetpl: _base.tpl
#Smartyの左デリミタ
leftdelimiter: "{"
#Smartyの右デリミタ
rightdelimiter: "}"
#出力する文字エンコード
encode:
#outputディレクトリをbuild時に中身を削除するか
buildclear: 1
#sitemap.xmlをつくるか
sitemap: 1
#robots.txtをつくるか
robotstxt: 1
#JavaScriptをminifyするか
compilejs: 1
#CSSをminifyするか
compilecss: 1
#lessをコンパイルするか
compileless: 1
#sassをコンパイルするか
compilesass: 1
#CoffeeScriptをコンパイルするか
compilecoffeescript: 1
#node.jsのlesscを使うか
uselessnode: 1
#lesscのパス
pathlessnode: auto
#ruby gemのsassを使うか
usesassruby: 1
#sassのパス
pathsassruby: auto
#ruby gemのsassを使うか
usecoffeescriptnode: 1
#coffeeのパス
pathcoffeescriptnode: auto
#認証情報などを記載したYAMLファイルのパス
credential:
#対応する言語の種類
languages: []
#sitemap.xmlで無視するファイル
ignoresitemaps: [ 404.html ]
#JavaScriptのminifyを行わないファイル
ignorecompilejs: []
#CSSのminifyを行わないファイル
ignorecompilecss: []
#Smartyの追加プラグインディレクトリ
smartypluginsdir: []