home:
  local: "http://localhost/Phest/sites/sample_plugin/output/local"
  production: "http://www.sample_plugin.com"
basetpl: "_base.tpl"
buildclear: 1
sitemap: 1
robotstxt: 1
compilejs: 1
compilecss: 1
plugins:
  - concat:
      output: "all.js"
      sources:[ "test.js", "test2.js" ]
  - copydir:
      from: "cptest1"
      to: "cptest2"
  -
     s3deploy:
       _button:
         label: デプロイテスト
         type: primary
         icon: ok-circle
       dryrun: true
       prefix: test/
       bucket: yourbucketname
       region: tokyo
       key: your access key
       secret: you secret key
  -
     s3deploy:
       _button:
         label: デプロイ
         type: success
         icon: cloud-upload
         confirm: true
       dryrun: false
       prefix: test/
       bucket: yourbucketname
       region: tokyo
       key: your access key
       secret: you secret key