home:
  local:"../sites/sample/output/local"
  production:"http://www.sample.com"
description: Phestの動作がわかるベーシックなサンプルです。{$_top}などの変数がどうセットされるのか、ナビゲーションメニューにおいて現在のメニュー位置にclassをあてる方法など参考にしてみてください。
basetpl: "_base.tpl"
buildclear:1
sitemap:1
robotstxt:1
compilejs:1
compilecss:1