home:
  local:"http://localhost/SmartBuilder/sites/sample_htmlmail/output/local"
  production:"http://www.sample.com"
basetpl: "_base.tpl"
encode:"jis"
buildclear:1
sitemap:0
robotstxt:0
compilejs:0
compilecss:0